### ISSUE TITLE
Evaluate multiline fn

### ISSUE THREAD

**Issue by smpallen99** [nurugger07/calliope#37]
I'd like the ability to generate the following EEx code.
```
 <%= for item <- items do %>
   <%= ExForm.form_for(item, "/" fn(f) -> 
          f
          |> ExForm.input(:name)
          |> ExForm.submit("save")
         end) %>
  <%= end %>
```
I have implemented it as the following haml:
```
 - for item <- items do
   = ExForm.form_for(item, "/" fn(f) -> 
     f
     |> ExForm.input(:name)
     |> ExForm.submit("save")
```
 A can submit a pull request soon if we agree on the syntax.

**Comment by nurugger07** [comment]
This looks good. This `|` is haml syntax for multiline but we may be able to get around it because we are in a script. http://haml.info/docs/yardoc/file.REFERENCE.html#multiline
