### ISSUE TITLE
Should pipe character be considered white space?

### ISSUE THREAD

**Issue by smpallen99** [nurugger07/calliope#38]
I noticed that the pipe character | is included in the white space regex. I question if that was intent. Tests still pass with it removed. Furthermore, it breaks my implementation of multiline fn, issue #37.

What was the intended purpose of including this character in white space? Note that ruby haml uses the pipe at the end of a line for string continuation.

**Comment by nurugger07** [comment]
I commented in the other issue but just incase someone reads this first. The `|` is haml syntax for multiline. http://haml.info/docs/yardoc/file.REFERENCE.html#multiline

**Comment by smpallen99** [comment]
Yes, I understand that `|` is haml syntax for multiline. But I understand that it goes as the last character on a line as explained the the multiline reference "It’s placed at the end of a line (after some whitespace) ". So, I believe that it does not belong in the regex that determines the indentation of a line. If so, then we probably don't have a conflict here :)

**Comment by nurugger07** [comment]
It may have been added at an earlier point but now is unnecessary. If it's removed and the test are passing we should be good to just take it out.

**Comment by nurugger07** [comment]
Closed with [PR #40](https://github.com/nurugger07/calliope/pull/40)
