### ISSUE TITLE
Syntax Issues with Attribute Values

### ISSUE THREAD

**Issue by hayesgm** [nurugger07/calliope#44]
I am looking to use Calliope for standard HTML rendering, but running into a serious issue.

```elixir
iex> Calliope.render "%a{href: page_path(@conn, 1)} Link"
"<a href='<%= page_path %>'(@conn 1)} Lin></a>"
```

The expected result is `<a href="/pages/1">Link</a>`. Notice the difference in attribute grouping, and the lack of final `k` on Link.

I would appreciate any feedback on how to get this case to work. I am using this via `phoenix_haml` and `phoenix`.

**Comment by nurugger07** [comment]
The `page_path/2` needs to be quoted. 

``` iex

iex(1)> Calliope.render "%a{href: '#\{page_path(conn, 1)}'} Link"
"<a href='<%= page_path(conn 1) %>'>Link</a>"

```

I did notice that there is a missing comma in the rendered `page_path/2`. Let me take a look at that because it should be rendering correctly.

**Comment by smpallen99** [comment]
Fixed
