### ISSUE TITLE
Old HAML hash rocket syntax breaks. 

### ISSUE THREAD

**Issue by jontonsoup** [nurugger07/calliope#46]
Sticking the generated app.layout into a HTML => HAML converter will produce a page that renders a raw string. 

```
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  %body
    .container{:role => "main"}
      .header
        %ul.nav.nav-pills.pull-right
          %li
            %a{:href => "http://www.phoenixframework.org/docs"} Get Started
        %span.logo
      %p.alert.alert-info{:role => "alert"}= get_flash(@conn, :info)
      %p.alert.alert-danger{:role => "alert"}= get_flash(@conn, :error)
      = @inner
    / /container
    %script{:src => static_path(@conn, "/js/app.js")}
    :javascript
      require("web/static/js/app")
```

Switching the hash rockets from 

`%p.alert.alert-info{:role => "alert"}= get_flash(@conn, :info)`

to 

`%p.alert.alert-info{role: "alert"}= get_flash(@conn, :info)`

fixes this issue. 

At a minimum, this should throw an error.

**Comment by nurugger07** [comment]
I'm doing a major overhaul of the tokenizer/parser to address some of these types of issues. The original regex seemed to out lived it's usefulness :)

I'll keep this open and update you when the fix is out.

**Comment by jontonsoup** [comment]
No worries! I'm holding off on adopting until there's partial support anyways. 




Just thought you might want a heads up if you didn't already know about it.




Keep up the awesome work! :)

**Comment by asymmetric** [comment]
Still getting bitten by this!

**Comment by smpallen99** [comment]
Support for hash rocket syntax added. Just note that right hand side of => must be a string. Use interpolation if you want to execute elixir code.
