### ISSUE TITLE
Incorrectly removed a comma in an attribute string

### ISSUE THREAD

**Issue by thawatchai** [nurugger07/calliope#49]
This line

`%a.btn.btn-default.btn-lg(href="" ng-click="loadMore(pagination, get_page)")"`

returns

`<a class="btn btn-default btn-lg" href="" ng-click="loadMore(pagination get_page)"></a>`

The expected result is

`<a class="btn btn-default btn-lg" href="" ng-click="loadMore(pagination, get_page)"></a>`

We use attribute strings to call Angular functions, so this bug breaks a lot of our code. Could you please fix it? Thank you very much. :smile:

**Comment by smpallen99** [comment]
Fixed
