### ISSUE TITLE
Incorrectly generates ng-class attribute

### ISSUE THREAD

**Issue by thawatchai** [nurugger07/calliope#53]
I've found another bug as follows:

`%li(ng-class="followees_tab")` generates `<li class="followees_tab" ng->`

It should generates `<li ng-class="followee_tabs">`

BTW, we start using more `calliope` now. This library will be important for the success of phoenix framework. Probably, we will have chances to send pull requests soon.

**Comment by smpallen99** [comment]
Fixed
