### ISSUE TITLE
Question: why use `-` instead of `=`?

### ISSUE THREAD

**Issue by rstacruz** [nurugger07/calliope#67]
I see docs say to use:

```haml
- if post do 
  %h1= post.title
```

But in EEx, you would've used `<%= if %>`, as that's the elixir way of doing things. Why does Calliope go with `-` instead of `=`?

**Comment by nurugger07** [comment]
This implementation is based on the original haml library. Haml is a markup language that has it's own rules. This library is an implementation to parse haml markup. The `-` is used evaluate but not insert into the document. Using `=` the code is evaluated and the output is inserted into the document.
