### ISSUE TITLE
link do .. end block

### ISSUE THREAD

**Issue by GBH** [nurugger07/calliope#80]
You can use `link` method as such:

```
link to: "/hello" do
  "world"
end
```

The only way to make it work in calliope is to write it like this:

```
= link to: "/hello" do
  world
- end
```

Is that normal? I'd expect it to function the same as conditionals being handled right now.

**Comment by smpallen99** [comment]
Try 
```
- link to: "/hello" do
  world
```

**Comment by GBH** [comment]
That did the trick. Thanks!
